// Autogenerated from java.template file

var mongoose = require('mongoose')
, Schema = mongoose.Schema
var AddressSchema = new mongoose.Schema({
  street:    {type:String},  city:    {type:String},  country:    {type:String}})

module.exports = mongoose.model('AddressSchema', AddressSchema)