// Autogenerated from java.template file

var mongoose = require('mongoose')

var AddressSchema = new mongoose.Schema({
  street: {type:String,  city: {type:String,  country: {type:String})

module.exports = mongoose.model('AddressSchema', AddressSchema)