// Autogenerated from java.template file

var mongoose = require('mongoose')
, Schema = mongoose.Schema
var BankSchema = new mongoose.Schema({
  bar:   [{ type: Schema.Types.ObjectId, ref: 'Address' }]   ,  ime:    {type:String}})

module.exports = mongoose.model('BankSchema', BankSchema)