// Autogenerated from java.template file

var mongoose = require('mongoose')

var BankSchema = new mongoose.Schema({
  bar: {type:Address,  ime: {type:String})

module.exports = mongoose.model('BankSchema', BankSchema)