// Autogenerated from java.template file

var mongoose = require('mongoose')
, Schema = mongoose.Schema
var CovekSchema = new mongoose.Schema({
  ime:    {type:String}})

module.exports = mongoose.model('CovekSchema', CovekSchema)