// Autogenerated from java.template file

var mongoose = require('mongoose'), Schema = mongoose.Schema
var validate = require('mongoose-validator');


var CovekSchema = new mongoose.Schema({
  ime:    {type:String, required: true 
}})

module.exports = mongoose.model('CovekSchema', CovekSchema)