// Autogenerated from java.template file

var mongoose = require('mongoose')

var CovekSchema = new mongoose.Schema({
  ime: {type:String})

module.exports = mongoose.model('CovekSchema', CovekSchema)